networks:
  pihole:
    name: pihole

services:
  pihole:
    container_name: pihole
    hostname: Pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    depends_on:
      pihole-unbound:
        condition: service_healthy
    networks:
      - pihole
    ports:
      - 53:53/udp     # Plain DNS UDP
      - 53:53/tcp     # Plain DNS TCP
      - 67:67/udp     # DHCP IPv4 UDP
      - 547:547/udp   # DHCP IPv6 UDP
      - 80:80/tcp     # HTTP Web Interface
    environment:
      - TZ=Europe/Berlin
      - PIHOLE_DNS_=127.0.0.1#5353
      - WEBPASSWORD=password
    cap_add:
      - NET_ADMIN
    volumes:
      - "./required/dnsmasq.d/10-pihole-dhcp.conf:/etc/dnsmasq.d/10-pihole-dhcp.conf"
      - "./required/dnsmasq.d/09-pihole-local-subdomains.conf:/etc/dnsmasq.d/09-pihole-local-subdomains.conf"
      - "./data/dnsmasq.d/:/etc/dnsmasq.d/"
      - "./data/pihole/:/etc/pihole/"
    healthcheck:
      test: "dig pi.hole @127.0.0.1 -p 53 || exit 1"
      start_period: 120s
      start_interval: 15s
      interval: 15s
      timeout: 5s
      retries: 3

  pihole-unbound:
    container_name: pihole-unbound
    image: mvance/unbound-rpi:latest
    restart: unless-stopped
    network_mode: service:pihole
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "./required/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf"
      - "./required/unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf"
      - "./required/unbound/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf"
      - "./required/unbound/srv-records.conf:/opt/unbound/etc/unbound/srv-records.conf"
    healthcheck:
      test: "drill google.com @127.0.0.1 -p 5353 || exit 1"
      start_period: 120s
      start_interval: 15s
      interval: 15s
      timeout: 5s
      retries: 3
